/*
 * coreMQTT <DEVELOPMENT BRANCH>
 * Copyright (C) 2022 Amazon.com, Inc. or its affiliates.  All Rights Reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * @file core_mqtt_v5_reason_codes.h
 * @brief Reason code constants for MQTT v5.0.
 */
#ifndef CORE_MQTT_V5_REASON_CODES_H
#define CORE_MQTT_V5_REASON_CODES_H

/* *INDENT-OFF* */
#ifdef __cplusplus
    extern "C" {
#endif
/* *INDENT-ON* */

/* Standard includes. */
#include <stdint.h>

/**
 * @ingroup mqtt_constants
 * @brief MQTT v5.0 reason codes.
 *
 * These constants define the reason codes for MQTT v5.0 packets.
 * The reason codes are grouped by the packet types they can be used with.
 */

/**
 * @brief Success reason codes.
 */
#define MQTT_REASON_SUCCESS                         ( ( uint8_t ) 0x00U )
#define MQTT_REASON_NORMAL_DISCONNECTION            ( ( uint8_t ) 0x00U )
#define MQTT_REASON_GRANTED_QOS_0                   ( ( uint8_t ) 0x00U )
#define MQTT_REASON_GRANTED_QOS_1                   ( ( uint8_t ) 0x01U )
#define MQTT_REASON_GRANTED_QOS_2                   ( ( uint8_t ) 0x02U )
#define MQTT_REASON_DISCONNECT_WITH_WILL_MESSAGE    ( ( uint8_t ) 0x04U )
#define MQTT_REASON_NO_MATCHING_SUBSCRIBERS         ( ( uint8_t ) 0x10U )
#define MQTT_REASON_NO_SUBSCRIPTION_EXISTED         ( ( uint8_t ) 0x11U )
#define MQTT_REASON_CONTINUE_AUTHENTICATION         ( ( uint8_t ) 0x18U )
#define MQTT_REASON_RE_AUTHENTICATE                 ( ( uint8_t ) 0x19U )

/**
 * @brief Error reason codes.
 */
#define MQTT_REASON_UNSPECIFIED_ERROR               ( ( uint8_t ) 0x80U )
#define MQTT_REASON_MALFORMED_PACKET                ( ( uint8_t ) 0x81U )
#define MQTT_REASON_PROTOCOL_ERROR                  ( ( uint8_t ) 0x82U )
#define MQTT_REASON_IMPLEMENTATION_SPECIFIC_ERROR   ( ( uint8_t ) 0x83U )
#define MQTT_REASON_UNSUPPORTED_PROTOCOL_VERSION    ( ( uint8_t ) 0x84U )
#define MQTT_REASON_CLIENT_IDENTIFIER_NOT_VALID     ( ( uint8_t ) 0x85U )
#define MQTT_REASON_BAD_USERNAME_OR_PASSWORD        ( ( uint8_t ) 0x86U )
#define MQTT_REASON_NOT_AUTHORIZED                  ( ( uint8_t ) 0x87U )
#define MQTT_REASON_SERVER_UNAVAILABLE              ( ( uint8_t ) 0x88U )
#define MQTT_REASON_SERVER_BUSY                     ( ( uint8_t ) 0x89U )
#define MQTT_REASON_BANNED                          ( ( uint8_t ) 0x8AU )
#define MQTT_REASON_SERVER_SHUTTING_DOWN            ( ( uint8_t ) 0x8BU )
#define MQTT_REASON_BAD_AUTHENTICATION_METHOD       ( ( uint8_t ) 0x8CU )
#define MQTT_REASON_KEEP_ALIVE_TIMEOUT              ( ( uint8_t ) 0x8DU )
#define MQTT_REASON_SESSION_TAKEN_OVER              ( ( uint8_t ) 0x8EU )
#define MQTT_REASON_TOPIC_FILTER_INVALID            ( ( uint8_t ) 0x8FU )
#define MQTT_REASON_TOPIC_NAME_INVALID              ( ( uint8_t ) 0x90U )
#define MQTT_REASON_PACKET_IDENTIFIER_IN_USE        ( ( uint8_t ) 0x91U )
#define MQTT_REASON_PACKET_IDENTIFIER_NOT_FOUND     ( ( uint8_t ) 0x92U )
#define MQTT_REASON_RECEIVE_MAXIMUM_EXCEEDED        ( ( uint8_t ) 0x93U )
#define MQTT_REASON_TOPIC_ALIAS_INVALID             ( ( uint8_t ) 0x94U )
#define MQTT_REASON_PACKET_TOO_LARGE                ( ( uint8_t ) 0x95U )
#define MQTT_REASON_MESSAGE_RATE_TOO_HIGH           ( ( uint8_t ) 0x96U )
#define MQTT_REASON_QUOTA_EXCEEDED                  ( ( uint8_t ) 0x97U )
#define MQTT_REASON_ADMINISTRATIVE_ACTION           ( ( uint8_t ) 0x98U )
#define MQTT_REASON_PAYLOAD_FORMAT_INVALID          ( ( uint8_t ) 0x99U )
#define MQTT_REASON_RETAIN_NOT_SUPPORTED            ( ( uint8_t ) 0x9AU )
#define MQTT_REASON_QOS_NOT_SUPPORTED               ( ( uint8_t ) 0x9BU )
#define MQTT_REASON_USE_ANOTHER_SERVER              ( ( uint8_t ) 0x9CU )
#define MQTT_REASON_SERVER_MOVED                    ( ( uint8_t ) 0x9DU )
#define MQTT_REASON_SHARED_SUBSCRIPTIONS_NOT_SUPPORTED ( ( uint8_t ) 0x9EU )
#define MQTT_REASON_CONNECTION_RATE_EXCEEDED        ( ( uint8_t ) 0x9FU )
#define MQTT_REASON_MAXIMUM_CONNECT_TIME            ( ( uint8_t ) 0xA0U )
#define MQTT_REASON_SUBSCRIPTION_IDENTIFIERS_NOT_SUPPORTED ( ( uint8_t ) 0xA1U )
#define MQTT_REASON_WILDCARD_SUBSCRIPTIONS_NOT_SUPPORTED ( ( uint8_t ) 0xA2U )

/**
 * @brief Reason codes for CONNACK packet.
 */
#define MQTT_REASON_CONNACK_SUCCESS                 MQTT_REASON_SUCCESS
#define MQTT_REASON_CONNACK_UNSPECIFIED_ERROR       MQTT_REASON_UNSPECIFIED_ERROR
#define MQTT_REASON_CONNACK_MALFORMED_PACKET        MQTT_REASON_MALFORMED_PACKET
#define MQTT_REASON_CONNACK_PROTOCOL_ERROR          MQTT_REASON_PROTOCOL_ERROR
#define MQTT_REASON_CONNACK_IMPLEMENTATION_SPECIFIC_ERROR MQTT_REASON_IMPLEMENTATION_SPECIFIC_ERROR
#define MQTT_REASON_CONNACK_UNSUPPORTED_PROTOCOL_VERSION MQTT_REASON_UNSUPPORTED_PROTOCOL_VERSION
#define MQTT_REASON_CONNACK_CLIENT_IDENTIFIER_NOT_VALID MQTT_REASON_CLIENT_IDENTIFIER_NOT_VALID
#define MQTT_REASON_CONNACK_BAD_USERNAME_OR_PASSWORD MQTT_REASON_BAD_USERNAME_OR_PASSWORD
#define MQTT_REASON_CONNACK_NOT_AUTHORIZED          MQTT_REASON_NOT_AUTHORIZED
#define MQTT_REASON_CONNACK_SERVER_UNAVAILABLE      MQTT_REASON_SERVER_UNAVAILABLE
#define MQTT_REASON_CONNACK_SERVER_BUSY             MQTT_REASON_SERVER_BUSY
#define MQTT_REASON_CONNACK_BANNED                  MQTT_REASON_BANNED
#define MQTT_REASON_CONNACK_BAD_AUTHENTICATION_METHOD MQTT_REASON_BAD_AUTHENTICATION_METHOD
#define MQTT_REASON_CONNACK_TOPIC_NAME_INVALID      MQTT_REASON_TOPIC_NAME_INVALID
#define MQTT_REASON_CONNACK_PACKET_TOO_LARGE        MQTT_REASON_PACKET_TOO_LARGE
#define MQTT_REASON_CONNACK_QUOTA_EXCEEDED          MQTT_REASON_QUOTA_EXCEEDED
#define MQTT_REASON_CONNACK_PAYLOAD_FORMAT_INVALID  MQTT_REASON_PAYLOAD_FORMAT_INVALID
#define MQTT_REASON_CONNACK_RETAIN_NOT_SUPPORTED    MQTT_REASON_RETAIN_NOT_SUPPORTED
#define MQTT_REASON_CONNACK_QOS_NOT_SUPPORTED       MQTT_REASON_QOS_NOT_SUPPORTED
#define MQTT_REASON_CONNACK_USE_ANOTHER_SERVER      MQTT_REASON_USE_ANOTHER_SERVER
#define MQTT_REASON_CONNACK_SERVER_MOVED            MQTT_REASON_SERVER_MOVED
#define MQTT_REASON_CONNACK_CONNECTION_RATE_EXCEEDED MQTT_REASON_CONNECTION_RATE_EXCEEDED

/**
 * @brief Reason codes for PUBACK packet.
 */
#define MQTT_REASON_PUBACK_SUCCESS                  MQTT_REASON_SUCCESS
#define MQTT_REASON_PUBACK_NO_MATCHING_SUBSCRIBERS  MQTT_REASON_NO_MATCHING_SUBSCRIBERS
#define MQTT_REASON_PUBACK_UNSPECIFIED_ERROR        MQTT_REASON_UNSPECIFIED_ERROR
#define MQTT_REASON_PUBACK_IMPLEMENTATION_SPECIFIC_ERROR MQTT_REASON_IMPLEMENTATION_SPECIFIC_ERROR
#define MQTT_REASON_PUBACK_NOT_AUTHORIZED           MQTT_REASON_NOT_AUTHORIZED
#define MQTT_REASON_PUBACK_TOPIC_NAME_INVALID       MQTT_REASON_TOPIC_NAME_INVALID
#define MQTT_REASON_PUBACK_PACKET_IDENTIFIER_IN_USE MQTT_REASON_PACKET_IDENTIFIER_IN_USE
#define MQTT_REASON_PUBACK_QUOTA_EXCEEDED           MQTT_REASON_QUOTA_EXCEEDED
#define MQTT_REASON_PUBACK_PAYLOAD_FORMAT_INVALID   MQTT_REASON_PAYLOAD_FORMAT_INVALID

/**
 * @brief Reason codes for PUBREC packet.
 */
#define MQTT_REASON_PUBREC_SUCCESS                  MQTT_REASON_SUCCESS
#define MQTT_REASON_PUBREC_NO_MATCHING_SUBSCRIBERS  MQTT_REASON_NO_MATCHING_SUBSCRIBERS
#define MQTT_REASON_PUBREC_UNSPECIFIED_ERROR        MQTT_REASON_UNSPECIFIED_ERROR
#define MQTT_REASON_PUBREC_IMPLEMENTATION_SPECIFIC_ERROR MQTT_REASON_IMPLEMENTATION_SPECIFIC_ERROR
#define MQTT_REASON_PUBREC_NOT_AUTHORIZED           MQTT_REASON_NOT_AUTHORIZED
#define MQTT_REASON_PUBREC_TOPIC_NAME_INVALID       MQTT_REASON_TOPIC_NAME_INVALID
#define MQTT_REASON_PUBREC_PACKET_IDENTIFIER_IN_USE MQTT_REASON_PACKET_IDENTIFIER_IN_USE
#define MQTT_REASON_PUBREC_QUOTA_EXCEEDED           MQTT_REASON_QUOTA_EXCEEDED
#define MQTT_REASON_PUBREC_PAYLOAD_FORMAT_INVALID   MQTT_REASON_PAYLOAD_FORMAT_INVALID

/**
 * @brief Reason codes for PUBREL packet.
 */
#define MQTT_REASON_PUBREL_SUCCESS                  MQTT_REASON_SUCCESS
#define MQTT_REASON_PUBREL_PACKET_IDENTIFIER_NOT_FOUND MQTT_REASON_PACKET_IDENTIFIER_NOT_FOUND

/**
 * @brief Reason codes for PUBCOMP packet.
 */
#define MQTT_REASON_PUBCOMP_SUCCESS                 MQTT_REASON_SUCCESS
#define MQTT_REASON_PUBCOMP_PACKET_IDENTIFIER_NOT_FOUND MQTT_REASON_PACKET_IDENTIFIER_NOT_FOUND

/**
 * @brief Reason codes for SUBACK packet.
 */
#define MQTT_REASON_SUBACK_GRANTED_QOS_0            MQTT_REASON_GRANTED_QOS_0
#define MQTT_REASON_SUBACK_GRANTED_QOS_1            MQTT_REASON_GRANTED_QOS_1
#define MQTT_REASON_SUBACK_GRANTED_QOS_2            MQTT_REASON_GRANTED_QOS_2
#define MQTT_REASON_SUBACK_UNSPECIFIED_ERROR        MQTT_REASON_UNSPECIFIED_ERROR
#define MQTT_REASON_SUBACK_IMPLEMENTATION_SPECIFIC_ERROR MQTT_REASON_IMPLEMENTATION_SPECIFIC_ERROR
#define MQTT_REASON_SUBACK_NOT_AUTHORIZED           MQTT_REASON_NOT_AUTHORIZED
#define MQTT_REASON_SUBACK_TOPIC_FILTER_INVALID     MQTT_REASON_TOPIC_FILTER_INVALID
#define MQTT_REASON_SUBACK_PACKET_IDENTIFIER_IN_USE MQTT_REASON_PACKET_IDENTIFIER_IN_USE
#define MQTT_REASON_SUBACK_QUOTA_EXCEEDED           MQTT_REASON_QUOTA_EXCEEDED
#define MQTT_REASON_SUBACK_SHARED_SUBSCRIPTIONS_NOT_SUPPORTED MQTT_REASON_SHARED_SUBSCRIPTIONS_NOT_SUPPORTED
#define MQTT_REASON_SUBACK_SUBSCRIPTION_IDENTIFIERS_NOT_SUPPORTED MQTT_REASON_SUBSCRIPTION_IDENTIFIERS_NOT_SUPPORTED
#define MQTT_REASON_SUBACK_WILDCARD_SUBSCRIPTIONS_NOT_SUPPORTED MQTT_REASON_WILDCARD_SUBSCRIPTIONS_NOT_SUPPORTED

/**
 * @brief Reason codes for UNSUBACK packet.
 */
#define MQTT_REASON_UNSUBACK_SUCCESS                MQTT_REASON_SUCCESS
#define MQTT_REASON_UNSUBACK_NO_SUBSCRIPTION_EXISTED MQTT_REASON_NO_SUBSCRIPTION_EXISTED
#define MQTT_REASON_UNSUBACK_UNSPECIFIED_ERROR      MQTT_REASON_UNSPECIFIED_ERROR
#define MQTT_REASON_UNSUBACK_IMPLEMENTATION_SPECIFIC_ERROR MQTT_REASON_IMPLEMENTATION_SPECIFIC_ERROR
#define MQTT_REASON_UNSUBACK_NOT_AUTHORIZED         MQTT_REASON_NOT_AUTHORIZED
#define MQTT_REASON_UNSUBACK_TOPIC_FILTER_INVALID   MQTT_REASON_TOPIC_FILTER_INVALID
#define MQTT_REASON_UNSUBACK_PACKET_IDENTIFIER_IN_USE MQTT_REASON_PACKET_IDENTIFIER_IN_USE

/**
 * @brief Reason codes for DISCONNECT packet.
 */
#define MQTT_REASON_DISCONNECT_NORMAL               MQTT_REASON_NORMAL_DISCONNECTION
#define MQTT_REASON_DISCONNECT_WITH_WILL_MESSAGE    MQTT_REASON_DISCONNECT_WITH_WILL_MESSAGE
#define MQTT_REASON_DISCONNECT_UNSPECIFIED_ERROR    MQTT_REASON_UNSPECIFIED_ERROR
#define MQTT_REASON_DISCONNECT_MALFORMED_PACKET     MQTT_REASON_MALFORMED_PACKET
#define MQTT_REASON_DISCONNECT_PROTOCOL_ERROR       MQTT_REASON_PROTOCOL_ERROR
#define MQTT_REASON_DISCONNECT_IMPLEMENTATION_SPECIFIC_ERROR MQTT_REASON_IMPLEMENTATION_SPECIFIC_ERROR
#define MQTT_REASON_DISCONNECT_NOT_AUTHORIZED       MQTT_REASON_NOT_AUTHORIZED
#define MQTT_REASON_DISCONNECT_SERVER_BUSY          MQTT_REASON_SERVER_BUSY
#define MQTT_REASON_DISCONNECT_SERVER_SHUTTING_DOWN MQTT_REASON_SERVER_SHUTTING_DOWN
#define MQTT_REASON_DISCONNECT_KEEP_ALIVE_TIMEOUT   MQTT_REASON_KEEP_ALIVE_TIMEOUT
#define MQTT_REASON_DISCONNECT_SESSION_TAKEN_OVER   MQTT_REASON_SESSION_TAKEN_OVER
#define MQTT_REASON_DISCONNECT_TOPIC_FILTER_INVALID MQTT_REASON_TOPIC_FILTER_INVALID
#define MQTT_REASON_DISCONNECT_TOPIC_NAME_INVALID   MQTT_REASON_TOPIC_NAME_INVALID
#define MQTT_REASON_DISCONNECT_RECEIVE_MAXIMUM_EXCEEDED MQTT_REASON_RECEIVE_MAXIMUM_EXCEEDED
#define MQTT_REASON_DISCONNECT_TOPIC_ALIAS_INVALID  MQTT_REASON_TOPIC_ALIAS_INVALID
#define MQTT_REASON_DISCONNECT_PACKET_TOO_LARGE     MQTT_REASON_PACKET_TOO_LARGE
#define MQTT_REASON_DISCONNECT_MESSAGE_RATE_TOO_HIGH MQTT_REASON_MESSAGE_RATE_TOO_HIGH
#define MQTT_REASON_DISCONNECT_QUOTA_EXCEEDED       MQTT_REASON_QUOTA_EXCEEDED
#define MQTT_REASON_DISCONNECT_ADMINISTRATIVE_ACTION MQTT_REASON_ADMINISTRATIVE_ACTION
#define MQTT_REASON_DISCONNECT_PAYLOAD_FORMAT_INVALID MQTT_REASON_PAYLOAD_FORMAT_INVALID
#define MQTT_REASON_DISCONNECT_RETAIN_NOT_SUPPORTED MQTT_REASON_RETAIN_NOT_SUPPORTED
#define MQTT_REASON_DISCONNECT_QOS_NOT_SUPPORTED    MQTT_REASON_QOS_NOT_SUPPORTED
#define MQTT_REASON_DISCONNECT_USE_ANOTHER_SERVER   MQTT_REASON_USE_ANOTHER_SERVER
#define MQTT_REASON_DISCONNECT_SERVER_MOVED         MQTT_REASON_SERVER_MOVED
#define MQTT_REASON_DISCONNECT_SHARED_SUBSCRIPTIONS_NOT_SUPPORTED MQTT_REASON_SHARED_SUBSCRIPTIONS_NOT_SUPPORTED
#define MQTT_REASON_DISCONNECT_CONNECTION_RATE_EXCEEDED MQTT_REASON_CONNECTION_RATE_EXCEEDED
#define MQTT_REASON_DISCONNECT_MAXIMUM_CONNECT_TIME MQTT_REASON_MAXIMUM_CONNECT_TIME
#define MQTT_REASON_DISCONNECT_SUBSCRIPTION_IDENTIFIERS_NOT_SUPPORTED MQTT_REASON_SUBSCRIPTION_IDENTIFIERS_NOT_SUPPORTED
#define MQTT_REASON_DISCONNECT_WILDCARD_SUBSCRIPTIONS_NOT_SUPPORTED MQTT_REASON_WILDCARD_SUBSCRIPTIONS_NOT_SUPPORTED

/**
 * @brief Reason codes for AUTH packet.
 */
#define MQTT_REASON_AUTH_SUCCESS                    MQTT_REASON_SUCCESS
#define MQTT_REASON_AUTH_CONTINUE_AUTHENTICATION    MQTT_REASON_CONTINUE_AUTHENTICATION
#define MQTT_REASON_AUTH_RE_AUTHENTICATE            MQTT_REASON_RE_AUTHENTICATE

/* *INDENT-OFF* */
#ifdef __cplusplus
    }
#endif
/* *INDENT-ON* */

#endif /* ifndef CORE_MQTT_V5_REASON_CODES_H */